#!/usr/bin/env python3
"""Generate the Privacy and Terms pages from the markdown in legal/.

Same rule as the wordmark and the share card: generated, not hand-written, so
the published page cannot drift from the document of record. legal/*.md is the
source of truth. Edit that, rerun this, commit both.

    python3 tools/legal/build.py

Writes site/privacy/index.html and site/terms/index.html. Those are Vite
multi-page entry points (see site/vite.config.js), so they build to
/privacy/ and /terms/ as real static URLs. No router, and no GitHub Pages
404.html redirect trick, both of which break deep links in ways that only show
up in production.

**The legal text is copied verbatim.** The only thing this changes is
structure. The generator that produced these documents emits <strong> for every
heading and <br> for every gap, which leaves a 15KB page with no heading
outline at all: a screen reader user gets one undifferentiated wall and no way
to jump between sections. Here the bold section titles become real <h2>s. No
wording is altered, reordered, added, or removed.
"""

import html
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

PAGES = [
    {
        "src": "legal/privacy-policy.md",
        "out": "site/privacy/index.html",
        "slug": "privacy",
        "title": "Privacy Policy",
        "description": "How Lifting Lab handles your data, your GDPR and "
                       "CCPA rights, and how to contact the data controller.",
    },
    {
        "src": "legal/terms-and-conditions.md",
        "out": "site/terms/index.html",
        "slug": "terms",
        "title": "Terms & Conditions",
        "description": "The terms you agree to when you download or use "
                       "Lifting Lab.",
    },
]

LINK = re.compile(r"\[([^\]]+)\]\((https?://[^)]+)\)")
BOLD = re.compile(r"\*\*(.+?)\*\*")


def inline(text: str) -> str:
    """Escape, then restore the inline markup the documents actually use.

    Order matters: escape first so any stray angle bracket in the prose is
    inert, then re-introduce only the tags this generator emits itself.
    """
    out = html.escape(text, quote=False)
    # The documents carry one raw <span> around the generator credit. It was
    # escaped a moment ago; unescape just that pair rather than allowing raw
    # HTML through generally.
    out = out.replace("&lt;span&gt;", "").replace("&lt;/span&gt;", "")
    out = LINK.sub(
        lambda m: f'<a href="{m.group(2)}" rel="noopener noreferrer" '
                  f'target="_blank">{m.group(1)}</a>',
        out)
    return BOLD.sub(r"<strong>\1</strong>", out)


def convert(md: str) -> str:
    """Markdown to a semantic fragment. Handles only what these files contain:
    bold-line headings, bullet lists, horizontal rules, and paragraphs."""
    blocks, buf, items = [], [], []

    def flush_para():
        if buf:
            blocks.append(f"<p>{inline(' '.join(buf))}</p>")
            buf.clear()

    def flush_list():
        if items:
            lis = "".join(f"<li>{inline(i)}</li>" for i in items)
            blocks.append(f"<ul>{lis}</ul>")
            items.clear()

    for raw in md.split("\n"):
        line = raw.rstrip()
        stripped = line.strip()

        if not stripped:
            flush_para(), flush_list()
            continue

        if stripped in ("* * *", "---", "***"):
            flush_para(), flush_list()
            blocks.append("<hr />")
            continue

        # "*   Item" is the only list form these documents use. Checked before
        # the heading rule because "**" would otherwise swallow it.
        if re.match(r"^\*\s{2,}", stripped):
            flush_para()
            items.append(re.sub(r"^\*\s+", "", stripped))
            continue

        # A whole line that is nothing but bold text is a section heading.
        whole = re.fullmatch(r"\*\*(.+?)\*\*", stripped)
        if whole:
            flush_para(), flush_list()
            text = whole.group(1).strip()
            blocks.append(f"<h2>{inline(text)}</h2>")
            continue

        flush_list()
        buf.append(stripped)

    flush_para(), flush_list()
    return "\n".join(blocks)


def page(body: str, meta: dict, updated: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>{meta['title']}: Lifting Lab</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta name="description" content="{meta['description']}" />
<link rel="canonical" href="https://liftinglab.app/{meta['slug']}/" />
<meta name="theme-color" content="#1A1A1A" />
<link rel="icon" type="image/svg+xml" href="/assets/mark.svg" />
<!-- Generated by tools/legal/build.py from {meta['src']}. Do not edit here. -->
<link rel="stylesheet" href="../src/legal.css" />
</head>
<body>
<a class="skip" href="#doc">Skip to the document</a>
<header class="legal-head">
  <a href="/" aria-label="Lifting Lab home">
    <img src="/assets/logo.svg" alt="Lifting Lab" width="156" height="45" />
  </a>
</header>
<main id="doc" class="legal">
<h1>{meta['title']}</h1>
<p class="legal-updated">Last updated {updated}</p>
{body}
</main>
<footer class="legal-foot">
  <nav aria-label="Legal and support">
    <a href="/">Home</a>
    <a href="/privacy/">Privacy</a>
    <a href="/terms/">Terms</a>
    <a href="mailto:contact@liftinglab.app">Contact</a>
  </nav>
</footer>
</body>
</html>
"""


def main() -> int:
    for meta in PAGES:
        src = ROOT / meta["src"]
        md = src.read_text()

        # The effective date is stated inside each document. Read it back out
        # rather than stamping today's date, so regenerating the page does not
        # silently claim the policy changed.
        found = re.search(r"effective as of (\d{4}-\d{2}-\d{2})", md)
        updated = found.group(1) if found else "on request"

        # The first bold line is the document's own title and becomes the <h1>,
        # so drop it from the body to avoid printing it twice.
        body = convert(re.sub(r"^\s*\*\*.+?\*\*\s*\n", "", md, count=1))

        out = ROOT / meta["out"]
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(page(body, meta, updated))
        print(f"wrote {meta['out']} ({out.stat().st_size // 1024} KB, "
              f"effective {updated})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
