#!/usr/bin/env python3
"""Compose the Open Graph card from the generated wordmark.

Same rule as the wordmark itself: this is generated, not drawn, so the card
can never drift from the logo. It inlines logo.svg's paths rather than
referencing the file, because a rasterizer resolving an external href is the
kind of thing that works locally and silently produces a blank card in CI.

The card carries the mark alone with no tagline. Text here would need Nunito
installed on whatever machine rasterizes it, and the whole point of outlining
the wordmark was to stop depending on that. The words live in og:title and
og:description, which is where a scraper reads them anyway.

    rsvg-convert is the rasterizer. Run:
        python3 tools/wordmark/social.py

Writes site/public/assets/og.svg and og.png (1200x630, the size Facebook,
X, LinkedIn, Slack and iMessage all crop from).
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOGO = ROOT / "site/public/assets/logo.svg"
OUT_SVG = ROOT / "site/public/assets/og.svg"
OUT_PNG = ROOT / "site/public/assets/og.png"

# The card, and the ground it sits on. BPColor.background, via tokens/colors.css.
WIDTH, HEIGHT = 1200, 630
GROUND = "#1a1a1a"
# The wordmark's own units are millimetres (155.772 x 45). Scaling to 720px
# wide leaves it a little under two thirds of the card, so the crop that some
# platforms apply to the edges cannot reach it.
MARK_WIDTH = 720.0


def main() -> int:
    svg = LOGO.read_text()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S)
    box = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg)
    if not inner or not box:
        print(f"could not parse {LOGO}", file=sys.stderr)
        return 1

    src_w, src_h = float(box.group(1)), float(box.group(2))
    scale = MARK_WIDTH / src_w
    mark_h = src_h * scale
    x = (WIDTH - MARK_WIDTH) / 2
    y = (HEIGHT - mark_h) / 2

    OUT_SVG.write_text(
        f'<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- Generated by tools/wordmark/social.py. Do not edit. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}">\n'
        f'  <rect width="{WIDTH}" height="{HEIGHT}" fill="{GROUND}"/>\n'
        f'  <g transform="translate({x:.3f} {y:.3f}) scale({scale:.6f})">'
        f"{inner.group(1)}</g>\n"
        f"</svg>\n"
    )

    try:
        subprocess.run(
            ["rsvg-convert", "-w", str(WIDTH), "-h", str(HEIGHT),
             "-o", str(OUT_PNG), str(OUT_SVG)],
            check=True, capture_output=True)
    except FileNotFoundError:
        print("rsvg-convert not found: brew install librsvg", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as e:
        print(e.stderr.decode(), file=sys.stderr)
        return 1

    print(f"wrote {OUT_SVG.relative_to(ROOT)} and "
          f"{OUT_PNG.relative_to(ROOT)} ({OUT_PNG.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
